In [2]:
from tensorflow import keras
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from tensorflow.keras.utils import to_categorical

import numpy as np
import pickle

In [3]:
def readfile(path):
    with open(path, encoding='utf-8') as f:
        text_in_string = f.read()
    return text_in_string

In [4]:
import spacy
nlp=spacy.load('en_core_web_sm',disable=['parser','tagger','ner'])
nlp.max_length= 1200000 

In [5]:
def separate_punc(text):
    return[word.text.lower() for word in nlp(text) if word.text not in '\n\n \n\n\n|"-#%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n \n\n\n\n\n \n\n\n\n \n ']

In [8]:
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [15]:
%cd /content/gdrive/MyDrive/Colab Notebooks




/content/gdrive/MyDrive/Colab Notebooks


In [16]:
data=readfile('Dataset.txt')
tokens=separate_punc(data)


/usr/local/lib/python3.9/dist-packages/spacy/pipeline/lemmatizer.py:211: UserWarning: [W108] The rule-based lemmatizer did not find POS annotation for one or more tokens. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
  warnings.warn(Warnings.W108)


In [17]:
tokens[:10]

['the', 'boy', 'who', 'lived', 'mr.', 'and', 'mrs.', 'dursley', 'of', 'number']

In [18]:
train_len=10 + 1
text_sequences= []
for i in range(train_len,len(tokens)):
  seq= tokens[i-train_len:i]
  text_sequences.append(seq)

In [19]:
text_sequences[2]

['who',
 'lived',
 'mr.',
 'and',
 'mrs.',
 'dursley',
 'of',
 'number',
 'four',
 'privet',
 'drive']

In [20]:
tokenizer=Tokenizer()

tokenizer.fit_on_texts(text_sequences)
sequences=tokenizer.texts_to_sequences(text_sequences)

vocabulary_size=len(tokenizer.word_counts)+1

In [21]:
sequences=np.array(sequences)

In [22]:
sequences[:3]

array([[   1,  153,   73, 1099,  159,    4,  265,  223,    9,  614,  325],
       [ 153,   73, 1099,  159,    4,  265,  223,    9,  614,  325,  615],
       [  73, 1099,  159,    4,  265,  223,    9,  614,  325,  615,  506]])

In [23]:
print(vocabulary_size)


6172


In [24]:
x = sequences[:, :-1]
y = sequences[:, -1]
seq_len = x.shape[1]
y=to_categorical(y,num_classes=vocabulary_size)

print(x[1:4])
print(y[1:4])

[[ 153   73 1099  159    4  265  223    9  614  325]
 [  73 1099  159    4  265  223    9  614  325  615]
 [1099  159    4  265  223    9  614  325  615  506]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [25]:
print(x.shape)
print(y.shape)

(90831, 10)
(90831, 6172)


In [26]:
import pickle
pickle.dump(tokenizer,open('mysimpletokenizer','wb'))

In [27]:
np.savez('processed_data', x, y)